name: Build and Deploy Java App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          echo "
          FROM openjdk:17-jdk-slim
          COPY build/libs/testing-1.0-SNAPSHOT.jar /app/testing-1.0-SNAPSHOT.jar
          CMD java -jar /app/testing-1.0-SNAPSHOT.jar
          " > Dockerfile

          docker build -t testing-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name testing-container testing-app

          echo "Waiting for 15 seconds for the application to start..."
          sleep 15

          docker ps -a

          curl --retry 5 --retry-delay 5 --max-time 30 http://localhost:8080 || { 
            echo "Application failed to start. Fetching logs..."; 
            docker logs testing-container; 
            exit 1; 
          }

      - name: Wait for 1 minute
        run: |
          echo "Waiting for 1 minute before stopping the container..."
          sleep 60

      - name: Stop Docker container
        run: |
          docker stop testing-container
          docker rm testing-container
          echo "Container stopped and removed."