name: Build and Deploy Java App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Build Docker Image
        run: |
          docker build -t testing-app .

      - name: Upload Docker Image as Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: testing-app-image
          path: /path/to/your/image

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker Image Artifact (optional)
        uses: actions/download-artifact@v4
        with:
          name: testing-app-image

      - name: Deploy Docker Container to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker run -d -p 8080:8080 --name testing-container testing-app
            echo "App started!"
            sleep 60  # Ждем 1 минуту
            docker stop testing-container
            echo "App stopped!"