name: Build and Deploy Java App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/${{ secrets.SERVER_USER }}/app"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Stopping the application..."
            pid=$(ps aux | grep 'java -jar' | grep -v grep | awk '{print $2}')
            if [ -n "$pid" ]; then
              kill -9 $pid
              echo "Java process killed."
            else
              echo "No Java process found."
            fi
            sleep 5

            echo "Starting the application..."
            nohup java -jar /home/${{ secrets.SERVER_USER }}/app/build/libs/testing-1.0-SNAPSHOT.jar > /home/${{ secrets.SERVER_USER }}/app/app.log 2>&1 &

            sleep 5
            if ps aux | grep -q '[j]ava -jar'; then
              echo "Application started successfully."
            else
              echo "Application failed to start. Check app.log for more details."
              tail -n 50 /home/${{ secrets.SERVER_USER }}/app/app.log
              exit 1
            fi